#! /bin/sh

# pgrep -x sxhkd > /dev/null || sxhkd &
# pgrep -x sxhkd > /home/force/.config/sxhkd/sxhkdrc || sxhkd &

sxhkd -c ~/.config/sxhkd/sxhkdrc &

picom &
~/.config/polybar_screens.sh
polybar -c ~/.config/polybar/config.ini top &

feh --bg-fill ~/Pictures/Backgrounds/bg.png



bspc monitor -d term web code irssi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
